fooding-core/src/main/java/im/fooding/core/model/reward/RewardAccount.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardChannel.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardLog.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardStatus.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardType.java
[BE-24] Reward 적립 관련 모델링
[도메인 모델링](https://www.notion.so/benkang/RewardEarning-1cc83feabad380abb940e18e0d9f0190?pvs=4)
- 리워드 적립 관련 모델링 엔티티 제작
- StoreService 모델링 엔티티가 제작되고 merge되면 추가 예정
=> [BE-24] Reward 적립 관련 모델링

fooding-core/src/main/java/im/fooding/core/model/reward/RewardLog.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardPoint.java
[BE-79] Reward 도메인 리모델링
[Reward 도메인 리모델링 계획](https://www.notion.so/benkang/Reward-1e283feabad380fda7e4e17e04503806?pvs=4)
- Reward 관련 기획 및 Figma를 통해 지난 회의 때 전달 받은 내용을 토대로 Reward 관련 도메인 리모델링
- RewardAccount -> RewardPoint 이름 변경
- StoreService 필드 삭제
=> [BE-79] Reward 도메인 리모델링

fooding-api/src/main/java/im/fooding/app/controller/admin/service/AdminStoreServiceController.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/service/CreateStoreServiceRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/service/RetrieveStoreServiceRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/service/StoreServiceResponse.java, fooding-api/src/main/java/im/fooding/app/service/admin/service/StoreServiceApplicationService.java, fooding-core/src/main/java/im/fooding/core/service/store/StoreServiceService.java
[BE-86] StoreService에 대한 Admin의 CRUD API 제작
- /admin/servcie 엔드 포인트 사용
- StoreService라는 도메인 명이 Store의 Service 객체와 이름이 겹치기에 사용시 유의 필요
=> [BE-86] ADMIN StoreService CRUD 제작

fooding-api/src/main/java/im/fooding/app/controller/app/waiting/AppWaitingController.java, fooding-api/src/main/java/im/fooding/app/controller/pos/waiting/PosWaitingController.java, fooding-api/src/main/java/im/fooding/app/dto/request/app/waiting/AppWaitingListRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/app/waiting/AppWaitingRegisterRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosUpdateWaitingContactInfoRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosUpdateWaitingTimeRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosWaitingCancelRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosWaitingListRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosWaitingMemoUpdateRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosWaitingOccupancyUpdateRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosWaitingRegisterRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/waiting/PosWaitingStatusUpdateRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppStoreWaitingResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppWaitingDetailsResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppWaitingLogResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppWaitingRegisterResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppWaitingUserResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/pos/waiting/PosStoreWaitingResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/pos/waiting/PosWaitingLogResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/pos/waiting/PosWaitingUserResponse.java, fooding-api/src/main/java/im/fooding/app/service/app/waiting/AppWaitingApplicationService.java, fooding-api/src/main/java/im/fooding/app/service/pos/waiting/PosWaitingService.java
- https://www.notion.so/benkang/waiting-api-1f183feabad380ee9012ec61dd0ebe98?pvs=4
- `app/controller/pos/waiting/` package 컨벤션을 지키지 않은 클래스들을 컨벤션에 맞게 변경했습니다.
- ex: `app/controller/waiting/`로 중간 pos, admin, app 등이 빠진 클래스들을 재 정리 했습니다.
- 코드 내용이 바뀐 부분은 없습니다.
- app과 pos에서 함께 사용하던 dto 도 분리했습니다.
- 더 늦기 전에 바로잡아야할 것 같아서 제일 먼저 했습니다..
=> [BE-131] waiting 관련 api 잘못된 패키지 올바르게 수정

fooding-api/src/main/java/im/fooding/app/controller/app/reward/AppRewardController.java, fooding-api/src/main/java/im/fooding/app/dto/request/user/reward/GetRewardLogRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/user/reward/GetRewardPointRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/user/reward/UpdateRewardPointRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/user/reward/GetRewardLogResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/user/reward/GetRewardPointResponse.java, fooding-api/src/main/java/im/fooding/app/service/user/reward/RewardApplicationService.java, fooding-core/src/main/java/im/fooding/core/global/exception/ErrorCode.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardLog.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardPoint.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardStatus.java, fooding-core/src/main/java/im/fooding/core/repository/reward/QRewardLogRepository.java, fooding-core/src/main/java/im/fooding/core/repository/reward/QRewardLogRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/repository/reward/QRewardPointRepository.java, fooding-core/src/main/java/im/fooding/core/repository/reward/QRewardPointRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/repository/reward/RewardLogRepository.java, fooding-core/src/main/java/im/fooding/core/repository/reward/RewardPointRepository.java, fooding-core/src/main/java/im/fooding/core/service/reward/RewardLogService.java, fooding-core/src/main/java/im/fooding/core/service/reward/RewardService.java
[ 백로그 ]
[BE-60](https://www.notion.so/benkang/APP-API-1d783feabad380ed865ae55d9dd9b8f5?pvs=4)
[BE-61](https://www.notion.so/benkang/APP-API-1d783feabad3809c9f0bd5325273efc5?pvs=4)
[BE-68](https://www.notion.so/benkang/APP-API-1df83feabad380ae95dcf449109f4a30?pvs=4)
APP 도메인에서의 Reward 적립, 내역 조회, 리워드 내역 조회 API 개발
- 리워드 적립 기능
- 리워드 로그 조회 기능
- 누적 리워드 조회 기능
=> [BE-60] / [BE-61] / [BE-68] - APP에서의 Reward 적립 및 내역 조회 API 제작

fooding-api/src/main/java/im/fooding/app/controller/admin/stores/AdminStoreController.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/store/AdminCreateStoreRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/store/AdminUpdateStoreRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/store/AdminStoreResponse.java, fooding-api/src/main/java/im/fooding/app/service/admin/store/AdminStoreService.java, fooding-api/src/main/java/im/fooding/app/service/user/store/UserStoreService.java, fooding-core/src/main/java/im/fooding/core/global/exception/GlobalExceptionHandler.java, fooding-core/src/main/java/im/fooding/core/model/store/Store.java, fooding-core/src/main/java/im/fooding/core/repository/store/QStoreRepository.java, fooding-core/src/main/java/im/fooding/core/repository/store/QStoreRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/service/store/StoreService.java
https://www.notion.so/benkang/ADMIN-API-1e983feabad380dcad3ed7d075ef446a?pvs=25
=> BE-92: Admin Store API 구현

fooding-api/src/main/java/im/fooding/app/controller/app/storeservice/AppStoreServiceController.java, fooding-api/src/main/java/im/fooding/app/service/admin/service/StoreServiceApplicationService.java, fooding-core/src/main/java/im/fooding/core/repository/store/StoreServiceRepository.java, fooding-core/src/main/java/im/fooding/core/service/store/StoreServiceService.java
[BE-97]
[BE-97 백로그](https://www.notion.so/benkang/APP-User-Store-StoreService-API-1f083feabad380caad78f859195da8fd?pvs=4)
- /app/storeservice/{id}   -> id는 storeId
-> storeId에는 User(CEO)의 정보가 담겨 있음
- Store ID를 통해 해당 Store에 가입된 StoreService 목록을 반환
=> [BE-97] APP에서 가게별 가입 서비스 조회 API 제작

fooding-api/src/main/java/im/fooding/app/controller/pos/reward/PosRewardController.java, fooding-api/src/main/java/im/fooding/app/dto/request/pos/reward/GetRewardRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/pos/reward/GetPosRewardResponse.java, fooding-api/src/main/java/im/fooding/app/service/pos/reward/PosRewardService.java, fooding-core/src/main/java/im/fooding/core/service/reward/RewardLogService.java
관련 백로그
[BE-62](https://www.notion.so/benkang/POS-API-1d783feabad3805d89bee4eade36b3f5?pvs=4)
[BE-62](https://www.notion.so/benkang/POS-API-1d783feabad38029916dd772ffc4e3ba?pvs=4)
- CEO의 매장에 관련된 리워드 적립 내역을 조회하는 API
- 발급한 리워드에 대해 대상의 적립을 취소하는 API
=> [BE-62][BE-63] - [POS] 리워드 적립 조회 및 적립 취소 API 제작

fooding-api/src/main/java/im/fooding/app/dto/response/app/store/AppStoreResponse.java
- #69
swagger에 필수값 여부가 표시되지 않아 프론트 측에서 혼란이 있는 것 같아 필수값 여부 정보를 추가했습니다.
=> [BE-100] [APP] User 별 관리 매장 목록 조회 API - swagger 필수값 인자 표시

fooding-api/src/main/java/im/fooding/app/dto/response/app/user/AppUserResponse.java
- #70 
swagger에 필수값 여부가 표시되지 않아 프론트 측에서 혼란이 있는 것 같아 필수값 여부 정보를 추가했습니다.
=> [BE-135] [APP] user 정보 조회 - swagger 필수값 인자 표시

fooding-api/src/main/java/im/fooding/app/controller/admin/device/AdminDeviceController.java, fooding-api/src/main/java/im/fooding/app/controller/ceo/device/CEODeviceController.java, fooding-api/src/main/java/im/fooding/app/service/user/device/DeviceApplicationService.java, fooding-core/src/main/java/im/fooding/core/repository/device/QDeviceRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/service/device/DeviceService.java
**[ 이슈 ]**
[CEO 디바이스 목록 조회 문제](https://forcu27.slack.com/archives/C08K7423KB3/p1747477998992529)
**<원인>**
1. Request 타입이 @RequestParam으로 되어 있었음 --> @ModelAttribute로 수정
2. BasicSearch의 기본 PageNum 값이 1로 되어 있음 --> Min(1)로 되어 있어 FE에서 넘어올 때 실제 페이지 숫자로 넘어오지만 리스트 배열의 위치이기에 -1을 해주는 로직이 필요
=> [BE-142] Device 목록 조회 API 수정

fooding-api/src/main/java/im/fooding/app/controller/user/review/UserReviewController.java, fooding-api/src/main/java/im/fooding/app/dto/request/user/review/CreateReviewRequest.java, fooding-api/src/main/java/im/fooding/app/service/user/review/UserReviewService.java, fooding-core/src/main/java/im/fooding/core/service/review/ReviewService.java
**< 백로그 >**
[USER 리뷰 작성](https://www.notion.so/benkang/User-API-1d783feabad38051b9c7c75cea6089f6?pvs=4)
[USER 리뷰 조회](https://www.notion.so/benkang/User-API-1d783feabad380b99fabf24e10b5af5e?pvs=4)
- Review 조회 기능의 경우 재혁님이 사전에 만들어 두셨습니다. 아주 살짝 수정했습니다.
=> [BE-37] [BE-38] - [USER] Review 조회 및 작성 API 제작

fooding-api/src/main/java/im/fooding/app/controller/app/user/AppUserController.java
- [[APP] 하드코딩된 인증된 사용자 응답 코드 작동 코드로 변경](https://www.notion.so/benkang/APP-20c83feabad380d498e0e017a652a541?source=copy_link)
- 하드코딩된 인증된 사용자 응답 코드 작동 코드로 변경
- front측 요청에 따라 빠르게 반영하려 합니다!
=> [BE-177] [APP] 하드코딩된 인증된 사용자 응답 코드 작동 코드로 수정

fooding-api/src/main/java/im/fooding/app/dto/response/user/reward/GetRewardLogResponse.java
**[ 백로그 ]**
[BE-181](https://www.notion.so/benkang/APP-Reward-Log-21383feabad380f19e1bed2e400a7a10?source=copy_link)
- GetRewardLogResponse 데이터에 createdAt 조회할 수 있도록 칼럼 추가
=> [BE-181] Reward Log 조회 시 적립 시간 조회 가능하도록 데이터 추가

fooding-api/src/main/java/im/fooding/app/controller/app/waiting/AppWaitingController.java, fooding-api/src/main/java/im/fooding/app/dto/request/app/waiting/AppWaitingListRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppStoreWaitingResponse.java, fooding-api/src/main/java/im/fooding/app/service/app/waiting/AppWaitingApplicationService.java
- [[APP] overview 가게 기준 API 생성](https://www.notion.so/benkang/APP-overview-API-21383feabad380199c6bc565ec0448d1?source=copy_link)
- [[APP] 가게 웨이팅 가게 기준 API 생성](https://www.notion.so/benkang/APP-API-21383feabad3808ebecff5ebc1334316?source=copy_link)
- 프론트 요청에 가게 기준으로 API 변경 요청에 따라 수정했습니다!
=> [BE-183] [BE-184] 가게 웨이팅 현황 조회, 목록 조회 가게 기준으로 조회하도록 변경

fooding-api/src/main/java/im/fooding/app/controller/app/storeservice/AppStoreServiceController.java, fooding-api/src/main/java/im/fooding/app/service/app/store/AppStoreServiceService.java
**[ 백로그 ]**
[BE-174](https://www.notion.so/benkang/StoreService-API-20c83feabad380209336ff2b7b2a95f9?source=copy_link)
- userId를 통해 해당 가게의 ownerId와 동일할 경우 조회 성공
- 동일하지 않은 경우 빈 결과 전송
=> [BE-174] StoreService 조회 시 userId를 통해 본인 소유의 가게인지 확인

fooding-api/src/main/java/im/fooding/app/controller/app/waiting/AppWaitingController.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/waiting/AppWaitingRegisterResponse.java, fooding-api/src/main/java/im/fooding/app/service/app/waiting/AppWaitingApplicationService.java
- [[APP] 웨이팅 등록 API 가게 기준으로 변경](https://www.notion.so/benkang/APP-API-21c83feabad380519d5eeab88572ecd7?source=copy_link)
- [APP] 웨이팅 등록 API 가게 기준으로 변경
- 응답값 requireMode 추가
=> [APP] 웨이팅 등록 API 가게 기준으로 변경

fooding-api/src/main/java/im/fooding/app/controller/admin/pointshop/AdminStorePointShopController.java, fooding-api/src/main/java/im/fooding/app/controller/ceo/stores/CeoStoreImageController.java, fooding-api/src/main/java/im/fooding/app/controller/ceo/stores/CeoStorePointShopController.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/pointshop/AdminCreatePointShopRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/pointshop/AdminSearchPointShopRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/pointshop/AdminUpdatePointShopRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/CeoCreateStoreRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/image/CeoCreateStoreImageRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/image/CeoSearchStoreImageRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/image/CeoUpdateStoreImageRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/pointshop/CeoCreatePointShopRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/pointshop/CeoSearchPointShopRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/pointshop/CeoUpdatePointShopRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/pointshop/AdminPointShopResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/ceo/store/CeoPointShopResponse.java, fooding-api/src/main/java/im/fooding/app/service/admin/store/AdminStorePointShopService.java, fooding-api/src/main/java/im/fooding/app/service/ceo/store/CeoStoreImageService.java, fooding-api/src/main/java/im/fooding/app/service/ceo/store/CeoStorePointShopService.java, fooding-api/src/main/java/im/fooding/app/service/ceo/store/CeoStoreService.java, fooding-core/src/main/java/im/fooding/core/global/exception/ErrorCode.java, fooding-core/src/main/java/im/fooding/core/global/exception/GlobalExceptionHandler.java, fooding-core/src/main/java/im/fooding/core/global/infra/slack/SlackClient.java, fooding-core/src/main/java/im/fooding/core/global/infra/slack/SlackConstant.java, fooding-core/src/main/java/im/fooding/core/model/pointshop/PointShop.java, fooding-core/src/main/java/im/fooding/core/model/store/Store.java, fooding-core/src/main/java/im/fooding/core/repository/pointshop/PointShopRepository.java, fooding-core/src/main/java/im/fooding/core/repository/pointshop/QPointShopRepository.java, fooding-core/src/main/java/im/fooding/core/repository/pointshop/QPointShopRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/service/pointshop/PointShopService.java
[BE-228](https://www.notion.so/benkang/ADMIN-CRUD-22883feabad38015ae6affc2eb080a08?source=copy_link)
[BE-230](https://www.notion.so/benkang/CEO-empty-string-22883feabad380e99996cc2cd8e90927?source=copy_link)
[BE-235](https://www.notion.so/benkang/CEO-CRUD-22d83feabad38040b5bec70b8c3d2d0e?source=copy_link)
- 백오피스 포인트샵 CRUD
- CEO 포인트샵 CRUD
- CEO 매장 생성 시, 이름 제외하고 다른건 emptyString
=> [BE-228] [BE-230] [BE-235]

fooding-api/src/main/java/im/fooding/app/dto/request/auth/AuthUpdateProfileRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/user/AdminUserResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/user/AppUserResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/auth/AuthUserResponse.java, fooding-api/src/main/java/im/fooding/app/service/admin/user/AdminUserService.java, fooding-api/src/main/java/im/fooding/app/service/auth/AuthService.java, fooding-core/src/main/java/im/fooding/core/model/user/User.java, fooding-core/src/main/java/im/fooding/core/service/user/UserService.java, fooding-core/src/test/java/im/fooding/core/service/user/UserServiceTest.java
[BE-234](https://www.notion.so/benkang/22c83feabad3808c9026c9b953310e08?source=copy_link)
유저 푸시 수신 여부 컬럼 추가 및 수정할 수 있도록 구현
=> [BE-234] 유저 서비스 앱 푸쉬 여부 추가

fooding-api/src/main/java/im/fooding/app/controller/user/coupons/UserCouponController.java, fooding-api/src/main/java/im/fooding/app/controller/user/store/UserStoreRewardController.java, fooding-api/src/main/java/im/fooding/app/dto/request/user/coupon/UserUseCouponRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/coupon/AdminUserCouponResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/app/coupon/AppUserCouponResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/ceo/coupon/CeoUserCouponResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/user/coupon/UserCouponResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/user/reward/UserPointShopResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/user/reward/UserStoreRewardResponse.java, fooding-api/src/main/java/im/fooding/app/service/admin/coupon/AdminUserCouponService.java, fooding-api/src/main/java/im/fooding/app/service/ceo/coupon/CeoUserCouponService.java, fooding-api/src/main/java/im/fooding/app/service/user/coupon/UserCouponAppService.java, fooding-api/src/main/java/im/fooding/app/service/user/coupon/UserStoreCouponService.java, fooding-api/src/main/java/im/fooding/app/service/user/reward/RewardApplicationService.java, fooding-api/src/main/java/im/fooding/app/service/user/store/UserStoreRewardService.java, fooding-core/src/main/java/im/fooding/core/event/coupon/RequestCouponListener.java, fooding-core/src/main/java/im/fooding/core/model/coupon/UserCoupon.java, fooding-core/src/main/java/im/fooding/core/model/reward/RewardPoint.java, fooding-core/src/main/java/im/fooding/core/repository/pointshop/QPointShopRepository.java, fooding-core/src/main/java/im/fooding/core/repository/pointshop/QPointShopRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/repository/reward/RewardPointRepository.java, fooding-core/src/main/java/im/fooding/core/service/coupon/UserCouponService.java, fooding-core/src/main/java/im/fooding/core/service/pointshop/PointShopService.java, fooding-core/src/main/java/im/fooding/core/service/reward/RewardService.java, fooding-core/src/test/java/im/fooding/core/service/coupon/UserCouponServiceTest.java
- [BE-236](https://www.notion.so/benkang/USER-22d83feabad38002a2ecc1fa488a96de?source=copy_link)
- [BE-237](https://www.notion.so/benkang/USER-API-22d83feabad380b589add7537d35f140?source=copy_link)
- 유저 포인트샵 상품 구매 
- 쿠폰 도메인 모델 테이블 번호, 포인트 추가 API 수정
=> [BE-236] [BE-238] 포인트샵 상품 구매 및 쿠폰 도메인 모델 테이블 번호, 포인트 추가 API 수정

fooding-api/src/main/java/im/fooding/app/controller/admin/menu/AdminMenuBoardController.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/menu/AdminMenuBoardCreateRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/menu/AdminMenuBoardListRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/admin/menu/AdminMenuBoardUpdateRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/menu/AdminMenuBoardResponse.java, fooding-api/src/main/java/im/fooding/app/service/admin/menu/AdminMenuBoardService.java, fooding-core/src/main/java/im/fooding/core/dto/request/menu/MenuBoardCreateRequest.java, fooding-core/src/main/java/im/fooding/core/dto/request/menu/MenuBoardUpdateRequest.java, fooding-core/src/main/java/im/fooding/core/global/exception/ErrorCode.java, fooding-core/src/main/java/im/fooding/core/model/menu/MenuBoard.java, fooding-core/src/main/java/im/fooding/core/repository/menu/MenuBoardRepository.java, fooding-core/src/main/java/im/fooding/core/service/menu/MenuBoardService.java
- [[ADMIN] MenuBoard CRUD API](https://www.notion.so/benkang/ADMIN-MenuBoard-CRUD-API-21183feabad380f2aafcee096344b84c?source=copy_link)
- [ADMIN] MenuBoard CRUD API
=> [BE-180] ADMIN MenuBoard CRUD API 개발

fooding-api/src/main/java/im/fooding/app/controller/ceo/region/CeoRegionController.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/region/CeoRegionListRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/store/CeoUpdateStoreRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/admin/store/AdminStoreResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/ceo/region/CeoRegionResponse.java, fooding-api/src/main/java/im/fooding/app/dto/response/ceo/store/CeoStoreResponse.java, fooding-api/src/main/java/im/fooding/app/service/ceo/region/CeoRegionService.java, fooding-core/src/main/java/im/fooding/core/model/store/Store.java
- [[CEO] Store 수정 및 조회시 regionId nullable 가능하도록 변경](https://www.notion.so/benkang/CEO-Store-regionId-nullable-24483feabad3801aaaa4e4e7cfa59d49?source=copy_link)
- [[CEO] 리전 리스트 API 생성](https://www.notion.so/benkang/CEO-API-24483feabad38047ac8ceaed88ca6994?source=copy_link)
- CEO Store 관련 API 응답 및 요청 region ID null 허용하도록 변경
- CEO 지역 리스트 조회 API 생성
=> [BE-268] [BE-269] CEO Store 관련 API 응답 및 요청

fooding-api/src/main/java/im/fooding/app/dto/request/admin/coupon/AdminCreateCouponRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/ceo/coupon/CeoCreateCouponRequest.java, fooding-api/src/main/java/im/fooding/app/dto/request/user/store/UserSearchStoreRequest.java, fooding-api/src/main/java/im/fooding/app/dto/response/user/coupon/UserStoreCouponResponse.java, fooding-api/src/main/java/im/fooding/app/service/user/store/UserStoreRewardService.java, fooding-core/src/main/java/im/fooding/core/global/exception/ErrorCode.java, fooding-core/src/main/java/im/fooding/core/model/coupon/Coupon.java, fooding-core/src/main/java/im/fooding/core/model/pointshop/PointShop.java, fooding-core/src/main/java/im/fooding/core/repository/coupon/QCouponRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/repository/pointshop/QPointShopRepositoryImpl.java
[BE-334](https://www.notion.so/benkang/USER-26783feabad38060bd9af631d77fb4bd?source=copy_link)
[BE-335](https://www.notion.so/benkang/null-26783feabad3807a84dde19e4b38d500?source=copy_link)
둘다 null 이면 스토어에 조회되도록 수정
발급 받을시 기간 검증 로직 수정
=> [BE-334] [BE-335] 쿠폰, 포인트샵 기간 제한 null 허용

fooding-api/src/main/java/im/fooding/app/dto/request/ceo/menu/CeoMenuListRequest.java, fooding-api/src/main/java/im/fooding/app/service/ceo/menu/CeoMenuService.java, fooding-core/src/main/java/im/fooding/core/repository/menu/MenuFilter.java, fooding-core/src/main/java/im/fooding/core/repository/menu/QMenuRepository.java, fooding-core/src/main/java/im/fooding/core/repository/menu/QMenuRepositoryImpl.java, fooding-core/src/main/java/im/fooding/core/service/menu/MenuService.java
- [CEO 메뉴 카테고리 필터링 조회 적용](https://www.notion.so/benkang/CEO-27083feabad380c7b320cead7ad5696a?source=copy_link)
- CEO 메뉴 카테고리 필터링 조회 적용
=> [BE-347] CEO 메뉴 카테고리 필터링 조회 적용
